/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.OrdemServico;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import projeto_db.Client;
import projeto_db.Projeto_DB;

/**
 *
 * @author Mateus
 */
public class AtualizarOS extends javax.swing.JPanel {

    /**
     * Creates new form AtualizarOS
     */
    
    private int id;
    JDialog jDialog;
    ArrayList<Client> clients;
    ShowOS showOS;
    
    public AtualizarOS() {
        initComponents();
    }
    public AtualizarOS(int id_cli, JDialog jd, ArrayList<Client> c, String cli, ShowOS so) {
        initComponents();
        this.id = id_cli;
        this.jDialog = jd;
        this.clients = c;
        this.showOS = so;
        for (int i = 0; i < this.clients.size(); i++) {
            clientsInpt.addItem(this.clients.get(i).getName());
        }
        clientsInpt.setSelectedItem(cli);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atualizarBtn = new javax.swing.JButton();
        equiInpt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        servInpt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        defInpt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tecInpt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        clientsInpt = new javax.swing.JComboBox<>();
        valInpt = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        infoLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voltarBtn = new javax.swing.JButton();

        atualizarBtn.setText("Atualizar");
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtnActionPerformed(evt);
            }
        });

        equiInpt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Serviço:");

        servInpt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Defeito:");

        defInpt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Técnico:");

        tecInpt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Valor:");

        clientsInpt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        valInpt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        valInpt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cliente:");

        infoLbl.setForeground(new java.awt.Color(255, 85, 85));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Equipamento:");

        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientsInpt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equiInpt)
                    .addComponent(defInpt)
                    .addComponent(servInpt)
                    .addComponent(tecInpt)
                    .addComponent(valInpt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 430, Short.MAX_VALUE))
                    .addComponent(infoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientsInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equiInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tecInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtnActionPerformed
        int clientID = -1;
        for (int i = 0; i < this.clients.size(); i++) {
            if(this.clients.get(i).getName() == clientsInpt.getSelectedItem()){
                clientID = this.clients.get(i).getId();
            }
        }
        String equipamento = equiInpt.getText();
        String defeito = defInpt.getText();
        String servico = servInpt.getText();
        String tecnico = tecInpt.getText();
        String valor = (valInpt.getText().replaceAll("\\.", "")).replaceAll(",", ".");

        if((clientID == -1) || equipamento.equals("") || defeito.equals("") || servico.equals("") || tecnico.equals("") || valor.equals("")){
            infoLbl.setText("A atualização não pode ter campos vazios");
        }else{
            infoLbl.setText("");
            String text = "Você tem certeza que deseja atualizar a Ordem de Serviço Nº" + this.id + "?";
            if(JOptionPane.showConfirmDialog(this, text, "Atenção", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                if(Projeto_DB.UpdateOS(this.id, equipamento, defeito, servico, tecnico, Float.parseFloat(valor), clientID)){
                    JOptionPane.showMessageDialog(this, "Ordem de Serviço atualizada com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    this.showOS.todoList();
                }else{
                    JOptionPane.showMessageDialog(this, "Não foi possível atualizar essa Ordem de Serviço.", "Erro [009]", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_atualizarBtnActionPerformed

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        this.jDialog.dispose();
    }//GEN-LAST:event_voltarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBtn;
    public javax.swing.JComboBox<String> clientsInpt;
    public javax.swing.JTextField defInpt;
    public javax.swing.JTextField equiInpt;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField servInpt;
    public javax.swing.JTextField tecInpt;
    public javax.swing.JFormattedTextField valInpt;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
